name: Build
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v2
    - name: Docker Login
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Build and push to Docker Hub
      id: hub_build
      uses: docker/build-push-action@v4
      with:
        push: true
        tags: compilerexplorer/dotnet-builder:latest
        cache-from: type=registry,ref=compilerexplorer/dotnet-builder:latest
        cache-to: type=inline
    - name: Docker Hub Image Digest
      run: echo ${{ steps.hub_build.outputs.digest }}
